export const CODE_SNIPPETS = {
  javascript: `function greet(name) {\n\tconsole.log("Hello, " + name + "!");\n}\n\ngreet("Alex");\n`,
  typescript: `type Params = {\n\tname: string;\n}\n\nfunction greet(data: Params) {\n\tconsole.log("Hello, " + data.name + "!");\n}\n\ngreet({ name: "Alex" });\n`,
  python: `def greet(name):\n\tprint("Hello, " + name + "!")\n\ngreet("Alex")\n`,
  java: `public class HelloWorld {\n\tpublic static void main(String[] args) {\n\t\tSystem.out.println("Hello World");\n\t}\n}\n`,
  csharp: `using System;\n\nnamespace HelloWorld\n{\n\tclass Hello {\n\t\tstatic void Main(string[] args) {\n\t\t\tConsole.WriteLine("Hello World in C#");\n\t\t}\n\t}\n}\n`,
  php: `<?php\n\n$name = 'Alex';\necho $name;\n`,
  ruby: `def greet(name)\n\tputs "Hello, #{name}!"\nend\n\ngreet("Alex")\n`,
  html: `<!DOCTYPE html>\n<html>\n<head>\n\t<title>Hello World</title>\n</head>\n<body>\n\t<h1>Hello, World!</h1>\n</body>\n</html>\n`,
  css: `body {\n\tfont-family: Arial, sans-serif;\n\tcolor: #333;\n}\n\nh1 {\n\tcolor: #007BFF;\n}\n`,
  sass: `$primary-color: #333;\n$font-stack: Arial, sans-serif;\n\nbody {\n\tfont: 100% $font-stack;\n\tcolor: $primary-color;\n}\n\nh1 {\n\tcolor: lighten($primary-color, 20%);\n}\n`,
  cpp: `#include <iostream>\n\nint main() {\n\tstd::cout << "Hello, World!" << std::endl;\n\treturn 0;\n}\n`,
  c: `#include <stdio.h>\n\nint main() {\n\tprintf("Hello, World!\\n");\n\treturn 0;\n}\n`,
  go: `package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello, World!")\n}\n`,
  solidity: `pragma solidity ^0.8.0;\n\ncontract HelloWorld {\n\tstring public greeting = "Hello, World!";\n}\n`,
  rust: `fn main() {\n\tprintln!("Hello, World!");\n}\n`,
};
